# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9799caa98dd61bc46445bc3614c5110d2952a9b7ae61f2c353ba2be5976ec9c613b2485cb833a7119b837803dd98777557647e5cc3c858888a63cdf50609b5b9

test:
  secret_key_base: 08a11a207ce4b159979db93b7c6f99f9616f503ee12ee7f8d17b2e352bd41ceecc1759831624cd7a6cf3c9d76057b6c308ec4b90bcb1277e742db8b4a65196fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
